### ISSUE TITLE
Can't create or join session

### ISSUE THREAD

**Issue by gtf974** [Geekid812/TrackmaniaBingo#1]
Hello. I'm not sure if this is the right place to report an issue.
I'm from Reunion Island, a french island near Madagascar and I just can't create or join a session.
Whenever I hit "Join session" or "Create session", the plugin darkens and crashes. I'm not able to click on anything. I'm forced to reload it.

My tag is Idotlebg

Thank you ;)

**Comment by Geekid812** [comment]
Hey @gtf974, thanks for reaching out. Could you please upload here your `Openplanet.log` file after executing the crash? That will help me troubleshoot the issue. You should find it in  `C:\Users\<Your Username>\OpenplanetNext\Openplanet.log`

**Comment by gtf974** [comment]
Of course, here you have it! 
[Openplanet.log](https://github.com/Geekid812/TrackmaniaBingo/files/9983034/Openplanet.log)

**Comment by gtf974** [comment]
Oh sorry, here is the one right after creating a room.

[Openplanet.log](https://github.com/Geekid812/TrackmaniaBingo/files/9983175/Openplanet.log)

**Comment by Geekid812** [comment]
Hmm, there seems to be nothing abnormal with the plugin. From what I can see, the issue is simply thay the plugin didn't manage to connect to the server. I'll have to check tomorrow on the server's status, but it seems to still be running from what I'm seeing. I'll keep you updated

**Comment by gtf974** [comment]
Allright! Maybe some other plugins interfering? Maybe the server ping locks me? Maybe it sees that I'm located so far away that it doesn't know if it can trust me ahah. I'll stay tuned! Thank you for your time

**Comment by gtf974** [comment]
Hello there! Any news ?

**Comment by Geekid812** [comment]
This weekend has unfortunately been busy for me, I should be able to check this tonight or tomorrow morning for sure. Sorry about that

**Comment by gtf974** [comment]
No problem, no rush needed! May I ask if there is any backup backend server url to send request to ?

**Comment by Geekid812** [comment]
The backend settings of the plugin are only for local development of the server, there is no alternative backend server. If you wanted, you could change the server URL to localhost and adjust the ports to use your local instance.

I think I do have figured out that your computer (or router, vpn or any intermediate) is sending invalid utf8 data to the plugin and that causes it to fail identification. At least I've seen some sort of error like that in the logs and I think it is related to this issue. I have no idea why that happens though.

If that is possible for you, could you try running a local server on your machine to check that something on your network is interfering? You can find a link to the server repo in the README.

**Comment by gtf974** [comment]
Course, I'll try that.

**Comment by gtf974** [comment]
Okay, I'm back! I started the server and I'm amazed that it works just fine. No problem logging into the server at all. No error prompted. I can host a game right now. (Listening on port 8080, and port TCP 6600 forwarded through localhost).

**Comment by Geekid812** [comment]
I doubt the timeout is the issue here. We're getting a UTF-8 parse error on our end, that means that somehow your traffic to the server is being intercepted and modified so that it's not what the plugin's protocol expects. Do you know of something that could cause this? I'm thinking it might be something specific to your network configuration given that other people can connect just fine.

**Comment by gtf974** [comment]
Mmh, I don't use any VPN or proxy. I only use a dynDNS with no-ip for Minecraft hosting but I don't think that's the issue because my IPV4 is  static. Other than that, all that I've changed on my end is some port forwarding.

**Comment by Geekid812** [comment]
Well, if we can't find out what is causing this issue, I might implement a hack that skips invalid UTF-8, to see if that lets you connect correctly. I'll let you know when you should be able to try this.

**Comment by gtf974** [comment]
As you wish! I don't want to bother you. If I can self host, no problem for me.

But sure, if you wanna test it out, I'll help you out.

**Comment by Geekid812** [comment]
Hey there, it's been a while since this issue was opened and some things have changed on the server side. Although I doubt the issue is just gone, if you are still having the issue please let me know so I can take a further look.

**Comment by gtf974** [comment]
Hey! Yeah I'm aware of the new update. Good news is I can create and join games. But I haven't tested the actual bingo yet. Yesterday we were on constant "Fetching maps from TMX", couldn't launch a single game. We assume that for now, your API requests to TMX got restricted. We are gonna try it tonight, to see if it solved out.
Anyway, my initial problem is solved! Thanks!
