### ISSUE TITLE
Some players don't "start" when the game is started

### ISSUE THREAD

**Issue by Geekid812** [Geekid812/TrackmaniaBingo#15]
Instead, they are stuck in the lobby while the others are in-game. The reasons for this are unknown.

**Comment by hinnie123** [comment]
One way to achieve this is to send a create game request whenever the client is already in a game. In the plugin menu the same lobby will visually be there, however on the server you're in a different lobby.

**Comment by Geekid812** [comment]
Do you know how this is accomplished? I don't understand in which case this double lobby bug would happen. Supposedly, the plugin disconnects itself from the server when leaving a lobby.

**Comment by hinnie123** [comment]
It's not something the plugin should do on its own, but rather if you send an additional create request from outside the plugin. Then you wont have to click the leave button in the plugin, so the connection will keep being alive, which allows the second create request to happen.
I'm not sure if this is related to what you experienced, however it is one way for the bug to happen.

**Comment by Geekid812** [comment]
That does happen from inside the plugin though, as seen by the problems experienced by Ameteratsu on tonight's stream. It also seems to "persist", such that disconnecting and reconnecting doesn't solve the issue.

**Comment by racacax** [comment]
Encountering the same issue. This error happens as soon as the game is started
![image](https://user-images.githubusercontent.com/9437635/210109366-4db957e9-060b-4c67-ad9f-bf511362d9d7.png)

**Comment by beavr27** [comment]
> Encountering the same issue. This error happens as soon as the game is started ![image](https://user-images.githubusercontent.com/9437635/210109366-4db957e9-060b-4c67-ad9f-bf511362d9d7.png)

I also get this issue quite often, I'd say once every 2 or 3 games I try to join.
I do have quite unstable internet so it could be something to do with that but not sure
