### ISSUE TITLE
royal maps

### ISSUE THREAD

**Issue by bigjoeshow** [Geekid812/TrackmaniaBingo#16]
is there a way for the map selection to be royal maps? a bunch of us in the royal family club are wondering.

**Comment by Geekid812** [comment]
It's possible that could be added, but right now Royal maps can't be played in solo mode, so that is very much compromised. This could be possible if we could make the plugin start the maps in Royal Time Attack mode locally, but that needs to be figured out.

**Comment by Geekid812** [comment]
Mappack selection has just landed on the development branch, soon you'll be able to use specific mappacks and play royal!
