### ISSUE TITLE
Allow selecting "Random Campaign maps"

### ISSUE THREAD

**Issue by Reloe** [Geekid812/TrackmaniaBingo#18]
Think it would make sense to have random campaign maps alongside the random Totd option.

**Comment by Geekid812** [comment]
By campaign, do you mean the nadeo campaigns or just generally any campaign? Anyway, there is already a plan to be able to select a specific mappack from TMX to pick maps from, so that should make it possible to play any campaign.

**Comment by Reloe** [comment]
I meant the official nadeo campaigns but yea selecting a mappack from TMX sounds very good.

**Comment by Geekid812** [comment]
The latest development version now has mappack selection mode! You should be able to play only campaign maps now.
