### ISSUE TITLE
issues 11.15

### ISSUE THREAD

**Issue by bigjoeshow** [Geekid812/TrackmaniaBingo#19]
we had a group of guys playing last night for multiple hours i just wanted to point out some of the issues we had that were ongoing. some of these may be covered but i just wanted to give a full rundown. all of these happened many many times over the course of hour play time ~5 hours and we had between 4-10 players (varied throughout the night)

-unable to join or create lobbies (mostly while maji and scrappie were streaming, i think i saw something about limited slots)
-host unable to start game (press start and the lobby doesnt start, kept spamming start until we gave up and tried to restart with new host.) 
-when starting game random players would get kicked from lobby
-when pressing play on a map, nothing would happen and you just couldnt join any map anymore
-when switching maps the entire TM game would freeze

overall we loved the mode, but much of our time was reloading the tool and restarting tm trying to get it to work.

**Comment by Geekid812** [comment]
A few bugs on this list have been fixed, you can check relevant issues: #11 #10 #24.

For maps that crash when you load them, the plugin has really no way to detect that beforehand. Potentially the plugin should detect when that happens and tell the server to change the map after the game started.

For players getting disconnected in the lobby, we don't have many leads on that yet, we're still investigating.
