### ISSUE TITLE
Connection Error - An error occured while communicating with the server. (Error 404)

### ISSUE THREAD

**Issue by assejn** [Geekid812/TrackmaniaBingo#26]
I disconnected from the server (without even realising that it happened), here's my log:
https://cdn.discordapp.com/attachments/186880781208125440/1042565843365658624/image.png

And here is the message that the other person in the recieved immediately after, plus their log:
https://img001.prntscr.com/file/img001/afZX-SyiSfaqMIpcn6GPWg.png
https://prnt.sc/YeiERnV4ea7o

**Comment by Geekid812** [comment]
This bug should have been fixed with the release of version 1.1, which introduces reconnection logic. Let me know if this bug happens again, but I think it should be gone now.
