### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Pex33** [Geekid812/TrackmaniaBingo#28]
Hi,
So I always get this error when i play with someone.
It never registers my times, i only get errors.
First time i tried playing bingo it worked and then never again.
Tried uninstalling the plugin, openplanet, and trackmania but the problem is still the same.
Also for example if i create a room and try to switch teams i get this error.
 
![Screenshot 2022-11-21 201839](https://user-images.githubusercontent.com/118767998/203140720-48b4b186-7adf-4c1d-9d6e-bf21315184c4.jpg)

[Openplanet.log](https://github.com/Geekid812/TrackmaniaBingo/files/10059887/Openplanet.log)

**Comment by pietrok29** [comment]
I am receiving the same error currently. I've also tried uninstalling everything and get the message.

**Comment by Geekid812** [comment]
Hey @pietrok29 and @Pex33, version 1.1 of the plugin is about to get released soon, which might fix this issue. Please let me know if you encounter this problem again after this update :pray:

**Comment by Pex33** [comment]
Just installed V1.1 and it now works flawlessly. thank you so much for fixing the issue. It´s a really fun game type when it works. Would be nice if maybe there could be like 3 or more teams instead of just 2. But hey maybe in the future! Thx again.

**Comment by pietrok29** [comment]
It now works for me as well! Thank you for the fix.

Love the plugin concept too!

**Comment by Geekid812** [comment]
Love to hear that! (also, that bug was just fixed :smile:)
