### ISSUE TITLE
fetching maps from tmx

### ISSUE THREAD

**Issue by bigjoeshow** [Geekid812/TrackmaniaBingo#30]
unable to start game due to plugin showing that its fetching maps from tmx. we have about 10 people trying to create a game and the same thing is happening to all of us.

**Comment by LukeTheVirus** [comment]
Self hosted server is working fine. Seems the official server is overloaded, guessing the tmx api is ratelimiting.

**Comment by Chris92de** [comment]
TMX doesn't really rate-limit however responses can be slow intermittently.
Are you running into a specific error from the TMX api?

**Comment by Geekid812** [comment]
It seems like the VPS has trouble contacting the TMX site as the connection seems to time out. I've tried to flush DNS and this doesn't seem to resolve it. I'll try to contact the TMX crew to try and find a solution promptly.

**Comment by Geekid812** [comment]
Update: Bingo is back! The VPS was blocked from TMX, it should be unlocked now! :tada:
