### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by Geekid812** [Geekid812/TrackmaniaBingo#36]
Something with icons on the bingo board to be more friendly towards colorblind players. Could be toggleable in the settings.

**Comment by cubenity** [comment]
It would be nice if the colours were changed to more contrasting ones, f.e. darker shade of green and lighter blue, so people with red-green colourblindness have an easier time. Making the colourblind mode a toggle would be a bit pointless, as I think a lot of streamers wouldn't bother, so just making the colours more distinguishable would be a good solution.

**Comment by Geekid812** [comment]
All of the team colors are configured server side, so if you can help me determine a list of 8 different colors (preferably with hex codes) that have as much contrast between them as possible to avoid these issues, it would be greatly appreciated. This could get complicated if we have to account for all types of colorblindness, but if you know of any helpful resources I would gladly take a look.

**Comment by cubenity** [comment]
Blue #0095FF
Red #D84315
Green #8BC34A
Cyan #4DD0E1
Pink #D81B60
Yellow #FFFF00

[Here's how it looks to different colourblindness types](https://imgur.com/a/lK24vED), I've tried to make it distinguishable for the first two types, as catering for blue-yellow colourblindness is a pretty difficult task, and it's very rare.

As for the last two colours, I suggest a shade of grey, like #424242, and maybe white, as they're probably the only colours left that most people will be able to distinguish easily, but I don't know, how readable will they be in the UI.

**Comment by cubenity** [comment]
https://daltonlens.org/colorblindness-simulator Here's a simulator, that should be decent for testing.

**Comment by Geekid812** [comment]
Thanks for the insight! I'll defenitely take into account these new colors.
It would be hard to integrate the white and gray colors however, because as you may already know gray is used to denote the absence of colour on the bingo board. I was only asking you for 8 colors to find out if it was possible to increase the amount of possible teams we could have while keeping this colorblind-friendliness requirement, but it seems it might be better to stick with 6 teams.

**Comment by Geekid812** [comment]
The new colorblind colors were added by default in the preview version, ready for the next update!

**Comment by cubenity** [comment]
ok, after seeing some feedback in various chats, i suggest changing pink to #E04980 and red back to #FF0000

**Comment by Geekid812** [comment]
I took notice of that. Team colors have been changed
