### ISSUE TITLE
disconnect from bingo

### ISSUE THREAD

**Issue by YueranYas** [Geekid812/TrackmaniaBingo#46]
does'nt happen often but somethimes i get this when the host starts the bingo , game starts for them but i get this error and can't play.

![bingoerror](https://user-images.githubusercontent.com/122943232/213034241-b27e440d-e04d-4ef1-a3b7-c833f4dd1e55.png)
![bingoerror](https://user-images.githubusercontent.com/122943232/213034496-05685a97-4f7a-4e9a-811f-5ad47dd25621.png)

**Comment by Geekid812** [comment]
Hey there! This issue is generally caused by internet connection problems (it's likely due to low/varying internet speeds. a fix for all of the network issues is underway
