### ISSUE TITLE
Team changes during game

### ISSUE THREAD

**Issue by LukeTheVirus** [Geekid812/TrackmaniaBingo#52]
During Spammiejs stream, for some reason the teams changed while the game was running.
At around 3 hours into this vod [https://www.twitch.tv/videos/1733946168](https://www.twitch.tv/videos/1733946168).
I was ingame so i was able to capture the log. As seen in the following image the team id for each member got increased by 1.
![Screenshot_1](https://user-images.githubusercontent.com/47090715/218149312-65850dd0-01ad-47b2-9269-9f39b9687c8e.png)
Full log: [Openplanet - Copy.log](https://github.com/Geekid812/TrackmaniaBingo/files/10709610/Openplanet.-.Copy.log)

**Comment by Geekid812** [comment]
Closing this old issue as it probably doesn't affect the new 4.0 version anymore.
