### ISSUE TITLE
Nonstop script exception (+4000 in like 15 seconds) 

### ISSUE THREAD

**Issue by dragondehielo** [Geekid812/TrackmaniaBingo#53]
With this I also had issue with maplist window not appearing and the Bingo plugin disappearing from the Plugin list when I tried to reset it
![bug](https://user-images.githubusercontent.com/82530211/218884802-eaf9084c-e679-4eac-9b53-7ff83346961c.png)

**Comment by atadier** [comment]
Thanks for reporting this. Do you know the circumstances under which circumstances this happened (just after countdown, in the middle or after a game) and do you know whether or not this is always reproducible?

**Comment by Geekid812** [comment]
Thanks for reporting this. Do you know under which circumstances this happened (after the countdown, in tje middle or after a game) and do you know whether or not this is always reproducible?
