### ISSUE TITLE
Failing to claim a map after ~10 minutes of gameplay

### ISSUE THREAD

**Issue by rusmack** [Geekid812/TrackmaniaBingo#54]
After about 10 minutes bingo does not claim a map for me(it does for my opponent though). Restarting the game and reconnecting fixes it until another 10 minutes go by. 
![image](https://user-images.githubusercontent.com/13278857/220611691-5e8c78d7-df6e-4652-befb-c90a4d70a9b4.png)

**Comment by rusmack** [comment]
After reinstalling openplanet and connecting to previously opened game, here are the full log: 
![image](https://user-images.githubusercontent.com/13278857/220615085-3bdc59b1-0d9c-4531-af4b-9514a93b66ba.png)

**Comment by Geekid812** [comment]
Map claim fail typically means you got disconnected, but in this case the plugin didn't detect being disconnected so it didn't try to reconnect you. However, this seems to be a network reliability problem, so even though this is a plugin bug, your network seems to be dropping the connection fairly quickly if nothing happens (or your internet is unreliable). If you suspect you are disconnected during a game, I would recommend you reload the plugin from the Openplanet menu to make sure you are synced. We will try to resolve the issue by implementing pinging soon.

**Comment by Geekid812** [comment]
Disconnection check were implemented in version 3.2, this problem shouldn't happen anymore.
