### ISSUE TITLE
Maps could not be loaded from TMX after name change

### ISSUE THREAD

**Issue by ByeKiroshi** [Geekid812/TrackmaniaBingo#58]
After i changed my name from ubisoft connect the bingo plugin stopped working. Everytime i try to create a room it says that the maps could not be loaded from tmx and i can't join other rooms or the plugin crashes.

**Comment by Geekid812** [comment]
Hey there, your name change is unlikely to be the cause of any issue in the plugin as your name is not stored in any way in the plugin or on the server.
It is more likely that at this moment there was a TMX outage, which indicates that the server will not be able to fetch maps for the bingo. This is a much more common problem, but we cannot do much at the moment as TMX is quite unstable on that regards. I hope you understand the issue!
