### ISSUE TITLE
"Unstable Plugin"

### ISSUE THREAD

**Issue by TASer1** [Geekid812/TrackmaniaBingo#59]
whenever i join a bingo game, the bingo plugin crashes and says an alert in the top left corner that the plugin had becomed unstable and it closed and i should check logs, same thing happens when i create on and when i copy code or add more than 5 teams. 
![image](https://github.com/Geekid812/TrackmaniaBingo/assets/88944947/7d130c72-eddc-42c3-a83e-56f1cebf2386)
![image](https://github.com/Geekid812/TrackmaniaBingo/assets/88944947/9e564135-6aa7-4405-ab54-b4906b129e40)
here are the logs

**Comment by Geekid812** [comment]
Hey, it would be more helpful to upload the whole log file here to help diagnose the issue more precisely. You can find the log in `C:/Users/USERNAME/OpenplanetNext/Openplanet.log`.

**Comment by Airekish** [comment]
I believe I'm experienceing the same issues as noted above. Essentially I get told the plugin became unstable whenever I change team, create more teams and when someone joins. I've also noticed everytime i open the bingo plugin after starting Trackmania I'm already in a room anf after waiting a couple seconds the plugin crashes again.
[Openplanet.log](https://github.com/Geekid812/TrackmaniaBingo/files/12446094/Openplanet.log)

**Comment by Geekid812** [comment]
The issue is known, I am working on fixing it.
