### ISSUE TITLE
Connectivity issues in version 4.1

### ISSUE THREAD

**Issue by chunxrulez** [Geekid812/TrackmaniaBingo#63]
Trackmania Bingo fails connection to servers and locks into offline mode. 
While other Openplanet Plugins seem to be working Trackmania Bingo fails to establish server connection. The Trackmania Client is running on Win 10 through Stream and Ubisoft Connect. 
[Openplanet.log](https://github.com/Geekid812/TrackmaniaBingo/files/13047116/Openplanet.log)

**Comment by Geekid812** [comment]
Hello! Can you please tell me what your ubisoft connect ID is? It may help with diagnosing the issue.

**Comment by chunxrulez** [comment]
Hey, ubisoft connect ID is 12809261-d862-4e75-ab95-e569f58ead1f

**Comment by Geekid812** [comment]
It looks like something with your player account is problematic. Loading your profile on trackmania.io throws an error: https://trackmania.io/#/player/12809261-d862-4e75-ab95-e569f58ead1f

Opening an issue in the trackmania.io repository can be a good starting point, as we depend on it to determine your country flag.

**Comment by chunxrulez** [comment]
I'm very sorry for the confusion. I send a wrong ID. The actual ID for the account is 24f151f9-cd05-49fe-9568-32819c17c49b

**Comment by Geekid812** [comment]
Have you tried again recently? Your account seems pretty new, maybe it was not in the trackmania.io database when you tried to connect for the first time.

**Comment by chunxrulez** [comment]
At the time of my last comment two days ago I still couldn't connect. Just now tried again and managed to successfully connect to the servers and play perfectly fine. So the issue might have been the newly created account. 
Thank you for your time. I hope not too many other people run into the same problem.
