### ISSUE TITLE
map list fills entire screen width

### ISSUE THREAD

**Issue by ezio416** [Geekid812/TrackmaniaBingo#64]
When in the window to select maps to play, the window is stretched to the entire width of my screen and doesn't allow for resizing.
<img width="1919" alt="Screenshot 2023-10-20 141647" src="https://github.com/Geekid812/TrackmaniaBingo/assets/37951898/6b2853b6-101e-4741-abad-6032244f178e">

**Comment by Geekid812** [comment]
The alignment of the reroll button is problematic here. I have removed it so that it will always be left aligned, so it should no longer cause issues once a new Bingo update is released (next version should be 4.2).
