### ISSUE TITLE
Clicking "Maps With Tag" crashes the plugin

### ISSUE THREAD

**Issue by visor841** [Geekid812/TrackmaniaBingo#67]
When creating a room, trying to set the map selection to "Maps with Tag" causes a plugin crash about a second later. Happens every time. Looking at the log, seems like there's a null tag or something.

Note: I am running Linux, but my friend running Windows has the exact same issue.

[Openplanet.log](https://github.com/Geekid812/TrackmaniaBingo/files/13406877/Openplanet.log)

**Comment by Geekid812** [comment]
Hey, sorry for a late reply, but this is a known issue. A fix is planned in the next update, expect a week of ETA before it is available in the stable Bingo. Sorry for that!
